# Generated by Django 3.2.9 on 2021-11-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100)),
                ('spotify', models.CharField(max_length=100)),
                ('youtube', models.CharField(max_length=100)),
            ],
        ),
    ]
