# Generated by Django 3.2.9 on 2021-11-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='name',
            field=models.CharField(default='song', max_length=100),
            preserve_default=False,
        ),
    ]
