# Generated by Django 3.2.9 on 2021-11-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_release_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='img',
            field=models.ImageField(default='abc', upload_to='images/'),
            preserve_default=False,
        ),
    ]
