# Generated by Django 3.2.9 on 2021-11-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_release_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
