# Generated by Django 3.2.9 on 2021-11-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_release_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='img',
        ),
    ]
