# Generated by Django 3.2.9 on 2021-11-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_release_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
