# Generated by Django 3.2.9 on 2021-12-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('youtube', models.CharField(max_length=400)),
                ('thumbnail_9x16', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
