# Generated by Django 3.2.9 on 2021-12-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_video_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_first', models.CharField(max_length=400)),
                ('facebook', models.CharField(max_length=400)),
                ('instagram', models.CharField(max_length=400)),
                ('youtube', models.CharField(max_length=400)),
                ('artist_image_wide', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
